steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t',
           'us-central1-docker.pkg.dev/crucial-binder-447418-k1/melda-100962200/gcp:${SHORT_SHA}',
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',
           'us-central1-docker.pkg.dev/crucial-binder-447418-k1/melda-100962200/gcp:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'gcp'
    - '--image'
    - 'us-central1-docker.pkg.dev/crucial-binder-447418-k1/melda-100962200/gcp:${SHORT_SHA}'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'  # Optional: allows public access to the service

images:
  - 'us-central1-docker.pkg.dev/crucial-binder-447418-k1/melda-100962200/gcp:${SHORT_SHA}'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
